# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j2P01eCpc3X-ZkRQW2FlzwLiFdbTTMWu
"""



def main():
    s=input("enter the day:")
    a=int(input("enter the day no:"))

    m={
        "mon":6,"tue":5,"wed":4,
        "thu":3,"fri":2,"sat":1,
        "sun":0
    }
    ans=0
    if a-m[s[:3]]>=1:
        ans=1+(a-m[s[:3]])//7
    print(ans)
main()