# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j2P01eCpc3X-ZkRQW2FlzwLiFdbTTMWu
"""



n=int(input("enter no of items:"))
arr=[]
for i in range(n):

    arr.append(int(input()))
    for i in sorted(arr):
        print(i,end=" ")